### PR TITLE
Fix sauce labs notify

### PR DESCRIPTION
**Pull request by ironsidevsquincy**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
stream page doesn't use saucelabs anymore… it uses the ft grid… so this code can be deletedd actually :)

**Comment by ironsidevsquincy** [comment]
Oh right. Is that something we're rolling out to all apps? Where can I see more info on this ft grid - usage, where is it, etc?

**Comment by matthew-andrews** [comment]
@ironsidevsquincy not yet, just trialling…  if we make our repos private we won't be able to use sauce labs anymore (unless we pay… which we decided, as an ft, not to do) so i wanted to understand whether we **could** use the internal grid to understand the benefits/disadvantages so that we can decide to move everything there, or overturn the saucelabs decision

**Comment by matthew-andrews** [comment]
details are here: https://sites.google.com/a/ft.com/technology/system/app/pages/customSearch?scope=search-ns&q=ft+grid

**Comment by matthew-andrews** [comment]
also worth saying we haven't decided to make repos private yet, but i wanted to understand what work we would have to do if we needed to do that

**Comment by ironsidevsquincy** [comment]
Ok. Nightwatch is still being run as part of stream's build - should this be turned off? And where are the build step are we running ft grid?

**Comment by matthew-andrews** [comment]
`nightwatch` runs on FT's Grid.

**Comment by matthew-andrews** [comment]
this is the command that runs nightwatch on the FT grid: https://github.com/Financial-Times/next-stream-page/blob/master/Makefile#L55

**Pull request closed without merging**
