### PR TITLE
styling changes from design

### PR DESCRIPTION
**Pull request by andygnewman**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
12 hour shift!?

**Comment by andygnewman** [comment]
Just leaving...

**Comment by matthew-andrews** [comment]
:+1: looks nice though

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-21/19:09-2317/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-21/19:09-2317/successes/index.html)

**Pull request merged**
