### PR TITLE
Remove broken tests

### PR DESCRIPTION
**Pull request by commuterjoy**
These don't work in production, so seems unfair to include them as smoke tests.

Master branch has been [failing for a week](https://circleci.com/gh/Financial-Times/next-stream-page) because of this.

### CODE REVIEW

**Comment by matthew-andrews** [comment]
i thought @i-like-robots was fixing these

**Comment by matthew-andrews** [comment]
:+1: for now, but we should fix them

**Comment by commuterjoy** [comment]
Yup, I couldn't actually see them being used anywhere, but I didn't look very hard.

**Comment by matthew-andrews** [comment]
they're pulled in on the front end…

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-stream-page/blob/09c541f5e397ba122b370a17007306269e98e785/client/components/stream/special-report.js#L5

**Comment by i-like-robots** [comment]
It's on the list, will prioritise

**Pull request merged**
