### PR TITLE
Use private cache

### PR DESCRIPTION
**Pull request by ironsidevsquincy**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
private for everything?

**Comment by ironsidevsquincy** [comment]
any reason not to? possibly json requests don't need it, but might do ab tests on them down the line, so probably easiest just to have a blanket rule

**Comment by matthew-andrews** [comment]
in that case we could do it in next-express?

**Comment by matthew-andrews** [comment]
:+1:

**Comment by ironsidevsquincy** [comment]
Yeah, would make sense if it's a global thing. We'll discuss tomorrow

**Pull request merged**
