### PR TITLE
WIP Dynamic loading & notification of new stories (FastFT)

### PR DESCRIPTION
**Pull request by andygnewman**
highlight

scroll

- Live streams fetch data every 60 seconds
- New stories are inserted into stream if the top of stream is in view...
- Or the user is alerted to the presence of new stories

### CODE REVIEW

**Comment by wheresrhys** [comment]
Are we doing anything to purge the fastft url on fastly when a new fastft story is published to es?

**Comment by i-like-robots** [comment]
@wheresrhys No... we did this last time https://github.com/Financial-Times/next-stream-page/issues/534

**Comment by i-like-robots** [comment]
Actually that was a different issue...

**Comment by matthew-andrews** [comment]
\o/

**Pull request merged**
