### PR TITLE
Add updated cards to stream pages

### PR DESCRIPTION
**Pull request by tom-parker**
@keirog

### CODE REVIEW

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-27/16:17-57/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-27/16:17-57/successes/index.html)

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-27/21:38-62/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-27/21:38-62/successes/index.html)

**Comment by keirog** [comment]
Would you mind fixing this please? Maybe just hide images for the S layout
s-layout
Otherwise :+1:

**Comment by tom-parker** [comment]
@keirog this should fix that issue hopefully

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-28/14:59-76/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-28/14:59-76/successes/index.html)

**Comment by keirog** [comment]
Thanks, yep sorted now :+1:

**Pull request merged**
