### PR TITLE
Darker borders in stickies

### PR DESCRIPTION
**Pull request by callumlocke**

### CODE REVIEW

**Comment by callumlocke** [comment]
apparently this is quite urgent and it's just a colour change so I'm skipping peer review, hope that's ok :)

**Comment by callumlocke** [comment]
Tests failed so ignore last comment :/

**Comment by matthew-andrews** [comment]
i think you're a victim of the US CAPI outage

**Comment by matthew-andrews** [comment]
oh no

**Comment by matthew-andrews** [comment]
just rerun CI without cache

**Comment by matthew-andrews** [comment]
> apparently this is quite urgent

colour changes are never **must do in the middle of the night** urgent.

**Comment by callumlocke** [comment]
fair point :)

I tried re-running without cache last night, and again just now, but it still fails. Any idea what might be wrong?

**Comment by matthew-andrews** [comment]
hmm it's an `o-ads` change:-

```
Unable to find a suitable version for o-element-visibility, please choose one:
    1) o-element-visibility#^1.0.0 which resolved to 1.0.1 and is required by next-stream-page
    2) o-element-visibility#^2.1.0 which resolved to 2.1.0 and is required by o-ads#2.10.4
```

**Comment by matthew-andrews** [comment]
I don't think this app even uses o-element-visibility:-

https://github.com/Financial-Times/next-stream-page/commit/1be7b4866e1bd08bb382156589c8021b8208c490

**Comment by callumlocke** [comment]
thanks!

**Comment by andygnewman** [comment]
I came across the same issue this morning and deleted o-element-visibility
from the bower.json of stream page as I couldn't find a usage.

On 18 February 2016 at 14:28, Callum Locke <notifications@github.com> wrote:

> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-stream-page/pull/916#issuecomment-185745371>
> .
>



-- 


*Andrew Newman *Junior Web Developer
FT.com Next

Financial Times

ft.com

One Southwark Bridge
London
SE1 9HL
UK

E: andrew.newman@ft.com <name.surname@companyname.com>


*Pearson *

Always Learning
Learn more at www.pearson.com

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Pull request merged**
