### PR TITLE
Add current nav transform to brand streams

### PR DESCRIPTION
**Pull request by i-like-robots**

### CODE REVIEW

**Comment by andygnewman** [comment]
Why? Doesn't this impact the custom header.

**Comment by i-like-robots** [comment]
> Why?

Lex, FT View etc. are in the navigation hierarchy 

> Doesn't this impact the custom header. 

I don't think so - the breadcrumb is standalone and unrelated to the stream header.

**Comment by andygnewman** [comment]
Just tested it out.

The only weirdness I can find is a brand, which has description (but no image) gets the related sections in the sub header. Like this Lex one.


screen shot 2016-05-31 at 17 32 14

**Comment by i-like-robots** [comment]
I think that's acceptable... as this all in flux but I guess it's not up to me =]

**Comment by andygnewman** [comment]
Yep, I think you're right. The sooner it just becomes the breadcrumb, the better.

**Comment by i-like-robots** [comment]
Sub sections now off when breadcrumb is on

**Comment by andygnewman** [comment]
LGTM

**Pull request merged**
