### PR TITLE
Remove Robot Week flag and custom fragment CSS

### PR DESCRIPTION
**Pull request by sumeetadur**
Removes the custom fragment CSS and the dependency on the robotWeek flag

### CODE REVIEW

**Comment by andygnewman** [comment]
Would it be better to remove the full profile for this page rather than just remove the specific robot transform?

**Comment by sumeetadur** [comment]
We just had a discussion about this. If we remove the full profile then the relatedTags transform is added through the default profile which we don't want. Keeping the profile with just the default transforms is the easiest way to have this right now but we need to discuss how to change this so that any streams with custom fragments or stickies will remove the relatedTags by default.

**Comment by andygnewman** [comment]
We're starting the Stream page redesign work now and the related tags element looks like it will be going, replaced by some form of Nav / Breadcrumb type approach, so when this is in we can change that.

**Comment by sumeetadur** [comment]
Perfect, thanks!

**Comment by sumeetadur** [comment]
@andygnewman can I get a 👍 ?

**Comment by andygnewman** [comment]
👍

**Pull request merged**
