### PR TITLE
Fix deduping

### PR DESCRIPTION
**Pull request by callumlocke**
Deduping sticky articles isn't working, meaning this page has some repeated headlines:

https://next.ft.com/stream/topicsId/NDdiMzAyNzctMTRlMy00Zjk1LWEyZjYtYmYwZWIwYWU2NzAy-VG9waWNz

### CODE REVIEW

**Comment by commuterjoy** [comment]
:+1: looks ok, with the caveat that it's me saying that.

**Comment by callumlocke** [comment]
thanks, you look trustworthy enough

**Comment by i-like-robots** [comment]
<nag>test?</nag>

**Comment by callumlocke** [comment]
Yes you are quite right
And that would have avoided this bug in the first place
Maybe I will write one

**Comment by callumlocke** [comment]
@i-like-robots I've added a test for the stickies transform. Can you have a look?

**Comment by i-like-robots** [comment]
:ship:

**Pull request merged**
