### PR TITLE
Remove references to next-card

### PR DESCRIPTION
**Pull request by adgad**
@andygnewman @andygout @keirog @GlynnPhillips 
Doesn't look like this was actively used anywhere anyway, so remove it all.

### CODE REVIEW

**Comment by andygnewman** [comment]
Think there might be some CSS that is imported from next-card

**Comment by adgad** [comment]
Yes this is a bigger change than I thought 😞

**Comment by adgad** [comment]
@andygnewman This okay now?

**Comment by andygnewman** [comment]
LGTM 👍

**Pull request merged**
