### PR TITLE
Ensure stream page templates are compatible with new o-grid

### PR DESCRIPTION
**Pull request by i-like-robots**
@kaelig

### CODE REVIEW

**Comment by kaelig** [comment]
lgtm :+1: 

Also, feel free to use the keyword "full-width" instead of "12" if you want to be extra explicit.

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-08-05/10:37-188/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-08-05/10:37-188/successes/index.html)

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-08-05/10:45-189/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-08-05/10:45-189/successes/index.html)

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-08-05/10:48-190/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-08-05/10:48-190/successes/index.html)

**Pull request merged**
