### PR TITLE
New stream controller and stream filters

### PR DESCRIPTION
**Pull request by i-like-robots**
- Prototype implementation of basic stream controller with transforms
- Example article model, basic filter by tag and live stream/open in stream plugins

Implements https://github.com/Financial-Times/next-stream-page/issues/871

Documentation:
https://github.com/Financial-Times/next-stream-page/wiki/Profiles
https://github.com/Financial-Times/next-stream-page/wiki/Transforms

### CODE REVIEW

**Comment by matthew-andrews** [comment]
quite neat :+1:

**Comment by callumlocke** [comment]
@i-like-robots how close are you to merging this, do you think? Don't want to rush you, but if it's going to be a while then I need to think about doing our brexit stuff in a different way so I can start showing work-in-progress to stakeholders

**Comment by i-like-robots** [comment]
I'm not going to be working again until Thursday, is that OK? Could a locally running instance + ngrok suffice for a few days? If the filters feature gets wrapped behind a flag then it's safe to go as is.

**Comment by callumlocke** [comment]
OK cool, I'll try ngrok

**Comment by callumlocke** [comment]
re:
> Could a locally running instance + ngrok suffice for a few days? If the filters feature gets wrapped behind a flag then it's safe to go as is.

I can use ngrok for now, but just to make you aware: we have a hard editorial deadline of **next Friday 15th Feb** to get our Brexit stuff online. So the earlier we can get this new stream controller merged into master the better, as ideally I'd like to be able to test our Brexit transforms in production at least a day or two early for testing. (Then we'll just flip the brexitStream flag to on-by-default on Friday.)

**Comment by callumlocke** [comment]
Er I just committed to your branch hope that's OK.

Everything looks good to me now.

**Comment by i-like-robots** [comment]
NP, hopefully the 'next gen' flag won't be around too long =]

**Pull request merged**
