### PR TITLE
Stop blowing up if search page is accessed without search term

### PR DESCRIPTION
**Pull request by i-like-robots**
Don't try and perform a search when no query is specified.

https://app.getsentry.com/nextftcom/ft-next-stream-page/group/72897394/

The page looks like :hankey: but it's better than an error.

### CODE REVIEW

**Comment by matthew-andrews** [comment]
:+1: :ship:

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-31/16:22-137/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-31/16:22-137/successes/index.html)

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-31/16:26-138/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-31/16:26-138/successes/index.html)

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-31/16:28-139/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/stream-page/2015-07-31/16:28-139/successes/index.html)

**Pull request merged**
