### PR TITLE
Decrease font sizes on photo diary headings

### PR DESCRIPTION
**Pull request by onishiweb**
Just realised I didn't commit the last changes to text sizes. Oops.

### CODE REVIEW

**Comment by andygnewman** [comment]
👍

**Comment by onishiweb** [comment]
Unsure why the tests have failed twice now. I've run them locally and they're passing :/

**Comment by ironsidevsquincy** [comment]
If you expand the `make tidy` section, you'll see the error being thrown by the app.

Upshot is, you'll need to remove this line - https://github.com/Financial-Times/next-stream-page/blob/master/.slugignore#L5

**Comment by andygnewman** [comment]
@ironsidevsquincy had meant to ask you about that line removal - saw it in your PR on article.

**Comment by ironsidevsquincy** [comment]
Yeah, express now checks to see what files should have been built based on the `.gitignore`, but that line was stopping the `.gitignore` being sent to the heroku box

**Comment by onishiweb** [comment]
Done, thanks for the heads up @ironsidevsquincy

**Comment by andygnewman** [comment]
👍  Best get this merged as the removal of the .gitignore is a dependency for other PRs

**Pull request merged**
